public static class QueensQueue
{
	public enum UnlockLocation
	{
		Any = 65535,
		GameScreen = 1,
		HomeScreen = 2,
		LevelCompleteScreen = 4
	}

	public enum UnlockPriority
	{
		DIFFICULTY_POPUP = 0,
		WEEKLY_LEADERBOARD = 1,
		ROYAL_TOURNAMENT = 2,
		DAILY_WIN_STREAK = 3,
		DAILY_REWARD = 4,
		BOOSTER = 5,
		FEATURE = 6,
		NO_ADS = 7,
		NEXT_LEVEL_FLOW = 8,
		SPECIAL_OFFER = 9,
		SPIN_WHEEL = 10,
		DAILY_CHALLENGE = 11,
		QUEENS_EVENT = 12,
		QUEENS_UNCLAIMED_GEMS = 13,
		NEW_JIGSAW_EVENT = 14,
		JIGSAW_PIECES = 15,
		DAILY_CHALLENGE_REWARD = 16,
		PVP_CHALLENGE_BUTTON = 17,
		PVP_UNFINISHED_MATCH = 18,
		DECORAMA = 19,
		LEADERBOARD = 20,
		PIGGY_BANK = 21,
		SHOP = 22,
		RATE_US_SOFT = 23,
		WIN_STREAK_BREAK = 24
	}
}
