using KWAds.Ads;

namespace KWAnalytics.Analytics
{
	[AnalyticsEvent("ad_completed", "An event for signalling that an ad has been completed")]
	public class AdCompletedEvent : AnalyticEvent
	{
		[AnalyticsEventParameter("ad_placement", "The placement of the ad in the game (previously called ad location at Kwalee)")]
		public AnalyticsParameter<string> adPlacement;

		[AnalyticsEventParameter("ad_unique_id", "The unique ID generated by the client when ad placement is reached.")]
		public AnalyticsParameter<string> adUniqueId;

		[AnalyticsEventParameter("ad_mediator", "The ad mediation platform used to serve the ad.")]
		public AnalyticsParameter<string> adMediator;

		[AnalyticsEventParameter("ad_revenue", "The revenue generated from the ad in US dollars.")]
		public AnalyticsParameter<float?> adRevenue;

		[AnalyticsEventParameter("ad_auction_instance", "The waterfall instance that provided this ad.")]
		public AnalyticsParameter<string> adAuctionInstance;

		[AnalyticsEventParameter("ad_network", "The ad provider's name.")]
		public AnalyticsParameter<string> adNetwork;

		[AnalyticsEventParameter("ad_auction_type", "The type of auction that delivered this ad.")]
		public AnalyticsParameter<string> adAuctionType;

		[AnalyticsEventParameter("ad_format", "The format of the ad (e.g. rewarded, interstitial, banner).")]
		public AnalyticsParameter<string> adFormat;

		[AnalyticsEventParameter("ad_creative_id", "An identifier of the ad creative shown (if available from the mediator). For cross promotion, this is the creative name from creative manager and if multiple creatives are shown as part of a single ad, this will be a space separated list of creative names.")]
		public AnalyticsParameter<string> adCreativeId;

		[AnalyticsEventParameter("ad_request_id", "The unique ID generated by the client on each ad request to tie together requests and downloads of ads.")]
		public AnalyticsParameter<string> adRequestId;

		[AnalyticsEventParameter("ad_placement_format", "The format of an ad was replaced by another (e.g. if a RV was replaced by an INT, then this parameter is set as interstitial.")]
		public AnalyticsParameter<string> adPlacementFormat;

		public AdCompletedEvent(CoreMediatorImpressionData impressionData, string adPlacement)
			: base(null)
		{
		}
	}
}
