namespace KWAnalytics.Analytics
{
	[AnalyticsEvent("ad_mediator_no_response", "An event for recording the response from the mediator when no ad is provided")]
	public class AdMediatorNoResponse : AnalyticEvent
	{
		[AnalyticsEventParameter("ad_mediator", "The ad mediation platform used to serve the ad.")]
		public AnalyticsParameter<string> adMediator;

		[AnalyticsEventParameter("ad_format", "The format of the ad (e.g. rewarded, interstitial, banner).")]
		public AnalyticsParameter<string> adFormat;

		[AnalyticsEventParameter("ad_request_id", "The unique ID generated by the client on each ad request to tie together requests and downloads of ads.")]
		public AnalyticsParameter<string> adRequestId;

		[AnalyticsEventParameter("ad_no_load_error_code", "The response from the mediator why no fill occurred.")]
		public AnalyticsParameter<int> adNoLoadErrorCode;

		public AdMediatorNoResponse(string adMediator, string adFormat, string adRequestId, int adNoLoadErrorCode)
			: base(null)
		{
		}
	}
}
