namespace KWAnalytics.Analytics
{
	[AnalyticsEvent("ad_request_sent", "Event for tracking ad requests to the mediator.")]
	public class AdRequestSentEvent : AnalyticEvent
	{
		[AnalyticsEventParameter("ad_mediator", "The ad mediation platform used to serve the ad.")]
		public AnalyticsParameter<string> adMediator;

		[AnalyticsEventParameter("ad_format", "The format of the ad (e.g. rewarded, interstitial, banner).")]
		public AnalyticsParameter<string> adFormat;

		[AnalyticsEventParameter("ad_request_id", "The unique ID generated by the client on each ad request to tie together requests and downloads of ads.")]
		public AnalyticsParameter<string> adRequestId;

		public AdRequestSentEvent(string adMediator, string adFormat, string adRequestId)
			: base(null)
		{
		}
	}
}
